name: A workflow for my Hello World file
on: push
#on:
#  workflow_dispatch:
jobs:
  job1:
    name: Hello world action
    runs-on: ubuntu-latest
    #steps:
  - uses: actions/checkout@v1

  job2:
    #uses: paulor27/hello-github/actions/.github/workflows/reusable-wf.yml
    runs-on: ubuntu-latest
    steps:
      - name: call reusable wf
        run: echo "HELLO"
      #- uses: ./action-a
      #  with:
      #    MY_NAME: "Mona"
