name: A workflow for my Hello World file
on: push
#on:
#  workflow_dispatch:
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: .github/workflows/reusable-wf
      #- uses: ./action-a
      #  with:
      #    MY_NAME: "Mona"
