name: A workflow for my Hello World file
on: push

jobs:
  job1:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: checkO
        uses: actions/checkout@v1

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: checkO
        uses: actions/checkout@v1
      - name: pwd
        run: pwd
      - name: ls -l
        run: ls -l
      - name: call reusable wf
        uses: reusable-wf.yml@main
      #uses: .github/workflows/reusable-wf.yml@main
      #uses: .github/workflows/reusable-wf.yml@main
      #uses: paulor27/hello-github/actions/.github/workflows/reusable-wf.yml@main
      #- uses: ./action-a
      #  with:
      #    MY_NAME: "Mona"
