name: A workflow for my Hello World file
#on: push
on:
  workflow_dispatch:
jobs:
  build:
    name: Called workflow
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "THIS IS THE CALLED WF - reusable-wf.yml"

