name: A workflow for my Hello World file
on:
  workflow_dispatch:

jobs:
  build:
    name: Called workflow
    runs-on: ubuntu-latest
    steps:
      - name: this is the reusable
        run: echo "THIS IS THE CALLED WF"

